/** Generated by scripts/sync-protocol-artifacts.mjs. */
export const contractsV2Provenance = {
	package: '@0xintuition/contracts-v2',
	version: '1.1.0-alpha.0',
	integrity:
		'sha512-vt9GFaFXYAeigLyl/4i6hPpLO4NBrZDyWJrM2M7aHuQ39/qSpxqMmIzetoAtpBWWx4AzM5wccUsXJvVST02saA==',
	abiFingerprint: '23e4cbd1a7686264e064aab0003a7fbcdaedc4d968828fc80f420d25b612e311',
	migrationModeAbiFingerprint: 'f45b684124c3966e98b69c14bd71bd59c29d342853619b502bb633afab0eaeff',
	bytecodeFingerprint: '14b962d2e352fb77ad50c0b5eed4fc5c15add2cfe739389c19a5b1147a507010',
	migrationModeBytecodeFingerprint:
		'63405db04afbdd063ce6406fdc43436ed7ceb319de4b0d3fbaf5400ac9d02246',
} as const;
