export const TrustSwapAndBridgeRouterAbi = [
	{ inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
	{ inputs: [], name: 'InvalidInitialization', type: 'error' },
	{ inputs: [], name: 'NotInitializing', type: 'error' },
	{
		inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
		name: 'OwnableInvalidOwner',
		type: 'error',
	},
	{
		inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
		name: 'OwnableUnauthorizedAccount',
		type: 'error',
	},
	{ inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
	{
		inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
		name: 'SafeERC20FailedOperation',
		type: 'error',
	},
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_AmountInZero', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InsufficientBridgeFee', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InsufficientETH', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InvalidAddress', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InvalidBridgeGasLimit', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InvalidPath', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InvalidRecipient', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InvalidRecipientDomain', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_InvalidToken', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_PathDoesNotEndWithTRUST', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_PathDoesNotStartWithToken', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_PathDoesNotStartWithWETH', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_PoolDoesNotExist', type: 'error' },
	{ inputs: [], name: 'TrustSwapAndBridgeRouter_TokenMismatch', type: 'error' },
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'newBridgeGasLimit', type: 'uint256' },
		],
		name: 'BridgeGasLimitSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'enum FinalityState',
				name: 'newFinalityState',
				type: 'uint8',
			},
		],
		name: 'FinalityStateSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
		name: 'Initialized',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'newMetaERC20Hub', type: 'address' }],
		name: 'MetaERC20HubSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
		],
		name: 'OwnershipTransferStarted',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint32', name: 'newRecipientDomain', type: 'uint32' },
		],
		name: 'RecipientDomainSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'newSlipstreamFactory', type: 'address' },
		],
		name: 'SlipstreamFactorySet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'newSlipstreamQuoter', type: 'address' },
		],
		name: 'SlipstreamQuoterSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'newSlipstreamSwapRouter', type: 'address' },
		],
		name: 'SlipstreamSwapRouterSet',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'user', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'tokenIn', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'amountIn', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'trustOut', type: 'uint256' },
			{ indexed: false, internalType: 'bytes32', name: 'recipientAddress', type: 'bytes32' },
			{ indexed: false, internalType: 'bytes32', name: 'transferId', type: 'bytes32' },
		],
		name: 'SwappedAndBridgedFromERC20',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'user', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'ethSwapped', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'trustOut', type: 'uint256' },
			{ indexed: false, internalType: 'bytes32', name: 'recipientAddress', type: 'bytes32' },
			{ indexed: false, internalType: 'bytes32', name: 'transferId', type: 'bytes32' },
		],
		name: 'SwappedAndBridgedFromETH',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'user', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'trustAmount', type: 'uint256' },
			{ indexed: false, internalType: 'bytes32', name: 'recipientAddress', type: 'bytes32' },
			{ indexed: false, internalType: 'bytes32', name: 'transferId', type: 'bytes32' },
		],
		name: 'TrustBridged',
		type: 'event',
	},
	{
		inputs: [],
		name: 'TRUST_ADDRESS',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'WETH_ADDRESS',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'acceptOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'bridgeGasLimit',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'trustAmount', type: 'uint256' },
			{ internalType: 'address', name: 'recipient', type: 'address' },
		],
		name: 'bridgeTrust',
		outputs: [{ internalType: 'bytes32', name: 'transferId', type: 'bytes32' }],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'finalityState',
		outputs: [{ internalType: 'enum FinalityState', name: '', type: 'uint8' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: '_owner', type: 'address' },
			{
				components: [
					{ internalType: 'address', name: 'slipstreamSwapRouter', type: 'address' },
					{ internalType: 'address', name: 'slipstreamFactory', type: 'address' },
					{ internalType: 'address', name: 'slipstreamQuoter', type: 'address' },
					{ internalType: 'address', name: 'metaERC20Hub', type: 'address' },
					{ internalType: 'uint32', name: 'recipientDomain', type: 'uint32' },
					{ internalType: 'uint256', name: 'bridgeGasLimit', type: 'uint256' },
					{ internalType: 'enum FinalityState', name: 'finalityState', type: 'uint8' },
				],
				internalType: 'struct RouterConfig',
				name: 'config',
				type: 'tuple',
			},
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'metaERC20Hub',
		outputs: [{ internalType: 'contract IMetaERC20Hub', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingOwner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'trustAmount', type: 'uint256' },
			{ internalType: 'address', name: 'recipient', type: 'address' },
		],
		name: 'quoteBridgeFee',
		outputs: [{ internalType: 'uint256', name: 'bridgeFee', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes', name: 'path', type: 'bytes' },
			{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
		],
		name: 'quoteExactInput',
		outputs: [{ internalType: 'uint256', name: 'amountOut', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'recipientDomain',
		outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'renounceOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'newBridgeGasLimit', type: 'uint256' }],
		name: 'setBridgeGasLimit',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'enum FinalityState', name: 'newFinalityState', type: 'uint8' }],
		name: 'setFinalityState',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newMetaERC20Hub', type: 'address' }],
		name: 'setMetaERC20Hub',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint32', name: 'newRecipientDomain', type: 'uint32' }],
		name: 'setRecipientDomain',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newSlipstreamFactory', type: 'address' }],
		name: 'setSlipstreamFactory',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newSlipstreamQuoter', type: 'address' }],
		name: 'setSlipstreamQuoter',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newSlipstreamSwapRouter', type: 'address' }],
		name: 'setSlipstreamSwapRouter',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'slipstreamFactory',
		outputs: [{ internalType: 'contract ICLFactory', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'slipstreamQuoter',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'slipstreamSwapRouter',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'tokenIn', type: 'address' },
			{ internalType: 'uint256', name: 'amountIn', type: 'uint256' },
			{ internalType: 'bytes', name: 'path', type: 'bytes' },
			{ internalType: 'uint256', name: 'minTrustOut', type: 'uint256' },
			{ internalType: 'address', name: 'recipient', type: 'address' },
		],
		name: 'swapAndBridgeWithERC20',
		outputs: [
			{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
			{ internalType: 'bytes32', name: 'transferId', type: 'bytes32' },
		],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes', name: 'path', type: 'bytes' },
			{ internalType: 'uint256', name: 'minTrustOut', type: 'uint256' },
			{ internalType: 'address', name: 'recipient', type: 'address' },
		],
		name: 'swapAndBridgeWithETH',
		outputs: [
			{ internalType: 'uint256', name: 'amountOut', type: 'uint256' },
			{ internalType: 'bytes32', name: 'transferId', type: 'bytes32' },
		],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'trustToken',
		outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
] as const;
