import { describe, expect, it } from 'vitest';

import { buildGen1Iid } from '../gen1.js';

/**
 * Golden vectors — these values are the spec's executable form. They match
 * `.planning/intuition-id/examples/` (generated by examples/generate.ts with
 * the same algorithm) and MUST NOT change without a gen2 migration (D12).
 */
describe('buildGen1Iid golden vectors', () => {
	it('company r4', () => {
		expect(buildGen1Iid('company', 4, { name: 'Anthropic' })).toBe(
			'int:gen1:company:r4:52fba5a65effdda2ed0fac8e219b6b77'
		);
	});

	it('book r3', () => {
		expect(buildGen1Iid('book', 3, { name: 'The Sovereign Individual' })).toBe(
			'int:gen1:book:r3:59a02a73cbe0d2a4223719fdc4d006ab'
		);
	});

	it('music-recording r3', () => {
		expect(buildGen1Iid('music-recording', 3, { name: 'One More Time' })).toBe(
			'int:gen1:music-recording:r3:187f0da4911954274a146463e981ed81'
		);
	});

	it('local-business r2 (name + geohash cell)', () => {
		expect(buildGen1Iid('local-business', 2, { name: 'Blue Bottle Coffee', geo7: '9q8yyw1' })).toBe(
			'int:gen1:local-business:r2:3e0068d38f80d5f50f265019e8623f09'
		);
	});

	it('movie r4 (name + year)', () => {
		expect(buildGen1Iid('movie', 4, { name: 'Inception', yearPublished: '2010' })).toBe(
			'int:gen1:movie:r4:fb681afe7d438cad73ae90a70f1cc55a'
		);
	});

	it('person r4', () => {
		expect(buildGen1Iid('person', 4, { givenName: 'Douglas', familyName: 'Adams' })).toBe(
			'int:gen1:person:r4:ecd9b23e74a6eb3380067d12349a669e'
		);
	});
});

describe('buildGen1Iid determinism properties', () => {
	it('is insensitive to field insertion order', () => {
		const a = buildGen1Iid('movie', 4, { name: 'Inception', yearPublished: '2010' });
		const b = buildGen1Iid('movie', 4, { yearPublished: '2010', name: 'Inception' });
		expect(a).toBe(b);
	});

	it('folds punctuation and case variants to one IID (D16)', () => {
		const curly = buildGen1Iid('music-recording', 3, { name: 'Don’t Stop Me Now' });
		const straight = buildGen1Iid('music-recording', 3, { name: "Don't Stop Me Now" });
		expect(curly).toBe(straight);
		expect(buildGen1Iid('music-group', 4, { name: 'KISS' })).toBe(
			buildGen1Iid('music-group', 4, { name: 'Kiss' })
		);
	});

	it('namespaces hashes by classification slug', () => {
		const business = buildGen1Iid('local-business', 4, { name: "Joe's Pizza" });
		const thing = buildGen1Iid('thing', 3, { name: "Joe's Pizza" });
		expect(business.split(':').at(-1)).not.toBe(thing.split(':').at(-1));
	});

	it('keeps the rung tag out of the hash', () => {
		const tagged = buildGen1Iid('movie', 4, { name: 'Inception' });
		const retagged = buildGen1Iid('movie', 5, { name: 'Inception' });
		expect(tagged.split(':').at(-1)).toBe(retagged.split(':').at(-1));
	});

	it('rejects empty recipes and empty values', () => {
		expect(() => buildGen1Iid('thing', 3, {})).toThrow();
		expect(() => buildGen1Iid('thing', 3, { name: '   ' })).toThrow();
	});
});
